version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - run: whoami
      - run: wpr -start GeneralProfile -start CPU -start DiskIO -start FileIO
      - run: sleep 5
      - run: Invoke-WebRequest https://makotom.net/env.php
      - run: Start-Process cmd.exe -ArgumentList "/c","echo CircleCI"
      - run: wpr -stop .\wpr.etl
      - store_artifacts:
          path: .\wpr.etl

